WITH BOOK_TOTAL_SALES AS (
SELECT 
    BOOK_ID, 
    SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY BOOK_ID)

SELECT
    T1.AUTHOR_ID, 
    T1.AUTHOR_NAME, 
    T2.CATEGORY, 
    SUM(T3.TOTAL_SALES * T2.PRICE) AS TOTAL_SALES
FROM AUTHOR T1
INNER JOIN BOOK T2 ON T1.AUTHOR_ID = T2.AUTHOR_ID
INNER JOIN BOOK_TOTAL_SALES T3 ON T2.BOOK_ID = T3.BOOK_ID
GROUP BY T1.AUTHOR_ID, T1.AUTHOR_NAME, T2.CATEGORY
ORDER BY T1.AUTHOR_ID, T2.CATEGORY DESC