WITH FAMILY_TABLE AS (
SELECT 
    CHILD.ID as CHILD, 
    PARENT.ID as PARENT, 
    GRAND_PARENT.ID as GRAND, 
    GREAT_GRAND_PARENT.ID as GREAT
FROM ECOLI_DATA CHILD
INNER JOIN ECOLI_DATA PARENT ON CHILD.PARENT_ID = PARENT.ID
INNER JOIN ECOLI_DATA GRAND_PARENT ON PARENT.PARENT_ID = GRAND_PARENT.ID
LEFT JOIN ECOLI_DATA GREAT_GRAND_PARENT ON GRAND_PARENT.PARENT_ID = GREAT_GRAND_PARENT.ID)

SELECT CHILD AS ID
FROM FAMILY_TABLE
WHERE GREAT IS NULL
ORDER BY ID ASC