WITH TMP AS (
SELECT 
    AO.ANIMAL_ID, 
    AO.NAME, 
    DATEDIFF(AI.DATETIME, AO.DATETIME) as diff
FROM ANIMAL_INS AI
INNER JOIN ANIMAL_OUTS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY diff desc),

TMP2 as (SELECT 
    *,
    ROW_NUMBER() OVER (ORDER BY diff) as RN
FROM TMP)

SELECT ANIMAL_ID, NAME
FROM TMP2
WHERE RN in (1,2)
ORDER BY RN asc



