WITH PERCENT_TABLE AS (
SELECT 
    ID, 
    SIZE_OF_COLONY, 
    PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY desc) AS PERCENT
FROM ECOLI_DATA)

SELECT 
    ID,
    CASE WHEN PERCENT <= 0.25 THEN 'CRITICAL'
         WHEN (PERCENT > 0.25) & (PERCENT <= 0.50) THEN 'HIGH'
         WHEN (PERCENT > 0.50) & (PERCENT <= 0.75) THEN 'MEDIUM'
         ELSE 'LOW'
         END AS 'COLONY_NAME'
FROM PERCENT_TABLE
ORDER BY ID ASC