WITH RECURSIVE GENERATION_TABLE AS (
SELECT ID, PARENT_ID, 1 as GENERATION
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL
UNION ALL

SELECT CHILD.ID, CHILD.PARENT_ID, PARENT.GENERATION + 1
FROM ECOLI_DATA CHILD
INNER JOIN GENERATION_TABLE PARENT ON CHILD.PARENT_ID = PARENT.ID),

CHILD_CHECK_TALBE AS (SELECT P.ID, P.GENERATION, C.ID AS CHILD
FROM GENERATION_TABLE P
LEFT JOIN ECOLI_DATA C ON P.ID = C.PARENT_ID
WHERE C.ID IS NULL)

SELECT COUNT(*) as COUNT, GENERATION
FROM CHILD_CHECK_TALBE
GROUP BY GENERATION
ORDER BY GENERATION ASC