WITH RECURSIVE HOURS AS (
SELECT 0 as HOUR
UNION ALL 
SELECT HOUR + 1
FROM HOURS
WHERE HOUR <= 22)

SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM HOURS T1
LEFT JOIN ANIMAL_OUTS T2 ON T1.HOUR = HOUR(T2.DATETIME)
GROUP BY HOUR