WITH REVIEW_CNT AS (
SELECT MEMBER_ID, COUNT(REVIEW_ID) as CNT
FROM REST_REVIEW
GROUP BY MEMBER_ID),

BEST_REVIEWER AS (SELECT MEMBER_ID
FROM REVIEW_CNT
WHERE CNT = (SELECT MAX(CNT) FROM REVIEW_CNT))

SELECT 
    T2.MEMBER_NAME,
    T3.REVIEW_TEXT, 
    DATE_FORMAT(T3.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM BEST_REVIEWER T1
INNER JOIN MEMBER_PROFILE T2 ON T1.MEMBER_ID = T2.MEMBER_ID
INNER JOIN REST_REVIEW T3 ON T1.MEMBER_ID = T3.MEMBER_ID
ORDER BY REVIEW_DATE asc, REVIEW_TEXT asc