SELECT 
    CHILD.ID, 
    CHILD.GENOTYPE as GENOTYPE, 
    PARENT.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA CHILD
LEFT JOIN ECOLI_DATA PARENT
ON CHILD.PARENT_ID = PARENT.ID
WHERE CHILD.GENOTYPE & PARENT.GENOTYPE = PARENT.GENOTYPE
ORDER BY CHILD.ID ASC