WITH YEAR_MAX AS (
SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as MAX_SIZE
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE))

SELECT 
    YEAR(T1.DIFFERENTIATION_DATE) as YEAR,
    T2.MAX_SIZE - T1.SIZE_OF_COLONY as YEAR_DEV,
    T1.ID
FROM ECOLI_DATA T1
INNER JOIN YEAR_MAX T2 ON YEAR(T1.DIFFERENTIATION_DATE) = T2.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC