WITH SCORE_TABLE AS (
SELECT EMP_NO, SUM(SCORE) as SCORE
FROM HR_GRADE
GROUP BY EMP_NO)

SELECT T1.SCORE, T1.EMP_NO, T2.EMP_NAME, T2.POSITION, T2.EMAIL
FROM SCORE_TABLE T1
INNER JOIN HR_EMPLOYEES T2 ON T1.EMP_NO = T2.EMP_NO
WHERE T1.SCORE = (SELECT MAX(SCORE) FROM SCORE_TABLE)